language: node_js
cache: npm
node_js:
  - 8
  - 10
  - 12

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: npx semantic-release
    - node_js: lts/*
      script:
        - npm run test
        - npm run coverage
