sudo: false
language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
node_js:
  - 4 # Node maintenance, keep up-to-date with https://github.com/nodejs/LTS
before_script:
  - npm prune
after_success:
  - npm run semantic-release
  - npm run coverage
